# Generated by Django 3.2.18 on 2023-06-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('cuit', models.CharField(max_length=100, null=True, verbose_name='CUIT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.IntegerField(default=0)),
                ('lote', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('pais', models.CharField(max_length=200, null=True, verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('productos', models.ManyToManyField(to='stock.Medicamento')),
                ('proveedor', models.ManyToManyField(to='stock.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.proveedor'),
        ),
    ]
