# Generated by Django 4.2 on 2023-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='precio',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
