# Generated by Django 4.2 on 2023-04-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_medicamento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='lote',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
