# Generated by Django 4.2 on 2023-04-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_pedido_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.medicamento'),
        ),
    ]
