# Generated by Django 4.2 on 2023-04-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='stock_User',
        ),
    ]
