# Generated by Django 4.2 on 2023-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_medicamento_id_remove_pedido_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ManyToManyField(to='stock.proveedor'),
        ),
    ]
