# Generated by Django 3.2.18 on 2023-06-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_pedido_vendedor_pedido_proveedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock_User',
            new_name='User',
        ),
    ]
