# Generated by Django 4.2 on 2023-06-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_rename_stock_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
