from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='inicio'),
    path('eliminar_cliente/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('clientes/editar/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('medicamentos/', views.lista_medicamentos, name='lista_medicamentos'),
    path('medicamentos/<int:medicamento_id>/', views.detalle_medicamento, name='detalle_medicamento'),
    path('medicamentos/alta/', views.alta_medicamento, name='alta_medicamento'),
    path('medicamentos/login/', views.login, name='login'),
    path('lista_pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('medicamentos/<int:medicamento_id>/editar/', views.editar_medicamento, name='editar_medicamento'),
    path('pedido/', views.cargar_pedido, name='pedido'),
    path('pedidos/eliminar/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
    path('pedidos/editar/<int:pedido_id>/', views.editar_pedido, name='editar_pedido'),
    path('pedidos/detalle/<int:pedido_id>/', views.detalle_pedido, name='detalle_pedido'),
    path('proveedores/editar/<int:proveedor_id>/', views.editar_proveedor, name='editar_proveedor'),
    path('proveedores/detalle/<int:proveedor_id>/', views.detalle_proveedor, name='detalle_proveedor'),
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('proveedores/', views.lista_proveedores, name='lista_proveedores'),
    path('alta_cliente/', views.alta_cliente, name='alta_cliente'),
    path('medicamento/<int:pk>/eliminar/', views.eliminar_medicamento, name='eliminar_medicamento'),
    path('cliente/<int:cliente_id>/', views.detalle_cliente, name='detalle_cliente'),
    path('alta_proveedor/', views.alta_proveedor, name='alta_proveedor'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/login/', views.login,name='login'),   
    path('proveedores/eliminar/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('pedidos/<int:pedido_id>/editar/', views.editar_pedido, name='editar_pedido'),
    path('pedidos/<int:pedido_id>/eliminar/', views.eliminar_pedido, name='eliminar_pedido'),
]